manifest:
  version: 0.7
 
  defaults:
    remote: nrfconnect

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v2.0.0
      import:
        path-prefix: deps

    # Golioth repository.
    - name: golioth
      path: deps/modules/lib/golioth
      revision: main
      url: https://github.com/golioth/golioth-zephyr-sdk.git

    # QCBOR
    - name: qcbor
      path: deps/modules/lib/qcbor
      revision: 17b5607b8c49b835d22dec3effa97b25c89267b3
      url: https://github.com/golioth/QCBOR.git

  self:
    path: app
